<?php

namespace Pterodactyl\Services\Plugins;

use Pterodactyl\Models\Plugin;
use Pterodactyl\Plugins\DesignTokenRegistry;
use Pterodactyl\Plugins\Permissions;
use Pterodactyl\Plugins\PluginManifest;

class PluginThemeService
{
    public const OVERLAY_CACHE_PATH = 'app/plugin-theme-overlay.css';

    public function __construct(
        private readonly DesignTokenRegistry $tokens,
        private readonly ManifestValidator $manifestValidator,
    ) {
    }

    /**
     * @return array<string, string>
     */
    public function resolvedTokensForSurface(string $surface): array
    {
        $base = $this->tokens->baseTokensForSurface($surface);
        $overlays = $this->mergedApprovedOverlays($surface);

        return array_merge($base, $overlays);
    }

    /**
     * @return array<string, string>
     */
    public function mergedApprovedOverlays(string $surface): array
    {
        $merged = [];

        $plugins = Plugin::query()
            ->where('enabled', true)
            ->orderBy('name')
            ->get();

        foreach ($plugins as $plugin) {
            if (!in_array(Permissions::UI_THEME, $plugin->effectivePermissions(), true)) {
                continue;
            }

            $approved = $plugin->approved_theme ?? [];
            if (!($approved['enabled'] ?? false)) {
                continue;
            }

            $surfaces = (array) ($approved['surfaces'] ?? []);
            if (!in_array($surface, $surfaces, true)) {
                continue;
            }

            $manifest = $this->readManifest($plugin);
            if (is_null($manifest)) {
                continue;
            }

            $theme = $manifest->uiTheme();
            if (is_null($theme)) {
                continue;
            }

            $allowedKeys = array_flip((array) ($approved['token_keys'] ?? []));
            foreach ($theme['tokens'] ?? [] as $key => $value) {
                if (!isset($allowedKeys[$key])) {
                    continue;
                }
                if (is_string($key) && is_string($value)) {
                    $merged[$key] = $value;
                }
            }
        }

        return $merged;
    }

    /**
     * @return array<int, array{plugin: Plugin, manifest: PluginManifest, theme: array<string, mixed>}>
     */
    public function themeContributors(): array
    {
        $output = [];
        foreach (Plugin::query()->orderBy('name')->get() as $plugin) {
            $manifest = $this->readManifest($plugin);
            if (is_null($manifest)) {
                continue;
            }

            $theme = $manifest->uiTheme();
            if (is_null($theme)) {
                continue;
            }

            $output[] = [
                'plugin' => $plugin,
                'manifest' => $manifest,
                'theme' => $theme,
            ];
        }

        return $output;
    }

    public function regenerateOverlayCache(): void
    {
        $css = $this->buildOverlayCss();
        $path = storage_path(self::OVERLAY_CACHE_PATH);
        file_put_contents($path, $css);
    }

    public function overlayCss(): string
    {
        $path = storage_path(self::OVERLAY_CACHE_PATH);
        if (is_file($path)) {
            return (string) file_get_contents($path);
        }

        $css = $this->buildOverlayCss();
        file_put_contents($path, $css);

        return $css;
    }

    private function buildOverlayCss(): string
    {
        $lines = ["/* Plugin theme overlays — generated by PluginThemeService */", ''];

        foreach (['client', 'admin'] as $surface) {
            $overlays = $this->mergedApprovedOverlays($surface);
            if ($overlays === []) {
                continue;
            }

            $selector = $surface === 'client'
                ? ':root, [data-pt-surface="client"]'
                : '[data-pt-surface="admin"], .ptero-plugin--admin';

            $lines[] = $selector . ' {';
            foreach ($overlays as $key => $value) {
                $lines[] = '    ' . $this->tokens->tokenToCssVariable($key) . ': ' . $value . ';';
            }
            $lines[] = '}';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    private function readManifest(Plugin $plugin): ?PluginManifest
    {
        $directory = PluginRegistry::directoryFor($plugin->id);
        if (!is_dir($directory)) {
            return null;
        }

        try {
            return $this->manifestValidator->readFromDirectory($directory);
        } catch (\Throwable) {
            return null;
        }
    }
}
